#!/usr/bin/env bash
sudo chmod +x ./scripts/updater
sudo chmod +x ./scripts/migrations
sudo chmod +x ./scripts/dependencycheck
sudo chmod +x ./scripts/clang-format-all
sudo chmod +x ./scripts/developer
sudo chmod +x ./scripts/format
sudo chmod +777 *
./scripts/updater
sudo chmod +x ./scripts/updater
sudo chmod +x ./scripts/migrations
sudo chmod +x ./scripts/dependencycheck
sudo chmod +x ./scripts/clang-format-all
sudo chmod +x ./scripts/developer
sudo chmod +x ./scripts/format
sudo chmod +777 *